// components/Player.tsx
"use client";

import { useState, useRef, useEffect } from 'react';

interface PlayerProps {
  songs: any[];
  currentIndex: number;
  onNext: () => void;
}

export default function Player({ songs, currentIndex, onNext }: PlayerProps) {
  const [playing, setPlaying] = useState(false);
  const [progress, setProgress] = useState('0%');
  const audioRef = useRef<HTMLAudioElement>(null);

  const song = songs[currentIndex];

  useEffect(() => {
    if (audioRef.current && playing) {
      audioRef.current.load();
      audioRef.current.play().catch(e => console.error("Play failed", e));
    }
  }, [currentIndex]);

  const togglePlayPause = () => {
    if (!audioRef.current) return;
    if (playing) {
      audioRef.current.pause();
    } else {
      audioRef.current.play().catch(e => console.error("Play failed", e));
    }
    setPlaying(!playing);
  };

  const onTimeUpdate = () => {
    if (!audioRef.current) return;
    const { currentTime, duration } = audioRef.current;
    const progressPercent = (currentTime / duration) * 100;
    setProgress(`${progressPercent}%`);
    if (progressPercent >= 100) {
      onNext();
    }
  };

  return (
    <div>
      <div className="wrapper">
        <span 
          onClick={togglePlayPause} 
          className={`play ${playing ? 'active' : ''}`}
        ></span>
        <img src={song.image} alt={song.title} />
      </div>
      <audio 
        ref={audioRef} 
        onTimeUpdate={onTimeUpdate}
        src={song.source}
      />
      <div className="progress-bar" style={{ width: progress }}></div>
      <h2>{song.title}</h2>
    </div>
  );
}

// src/components/Player.vue

<template>
  <div v-if="this.songs.length > 0">
    <div class="wrapper">
      <!--<span class="play"></span>-->
      <img :src="this.songs[this.currentSong].image" alt="">
    </div>
    <audio ref="player" @timeupdate="onTimeUpdateListener">
      <source :src="this.songs[this.currentSong].source" type="audio/mpeg">
    </audio>
    <div class="progress-bar" :style="{width: this.progress}"></div>
    <h2>{{ this.songs[this.currentSong].title }}</h2>
  </div>
</template>

<script>

const DURATION = 2;

export default {
  name: 'Player',
  props: ['songs'],
  data() {
    return {
      currentSong: 0,
      currentTime: 0,
      progress: 0
    }
  },
  mounted() {
    setTimeout(()=>{
      this.$refs.player.play();
    }, 2000)
  },
  computed: {
    song() {
      this.$refs.player.play();
      return this.songs[this.currentSong];
    },
    player() {
      return this.$refs.player;
    }   
  },
  methods: {
    nextSong() {
      let trackSource = this.songs[this.currentSong++].source;
      trackSource === "" ? this.songs[this.currentSong + 2].source : trackSource;
      this.player.load();
      this.player.play();
    },
    onTimeUpdateListener() {
      this.currentTime = this.$refs.player.currentTime;
      this.progress =(this.currentTime /  this.$refs.player.duration) * 100 + "%";
      if(this.progress === '100%') {
        this.nextSong();
      }
    }
  }
}
</script>
