// components/Roller.tsx
"use client";

interface RollerProps {
  songs: any[];
  activeIndex: number;
}

export default function Roller({ songs, activeIndex }: RollerProps) {
  const nextTwo = activeIndex + 3;

  const getActiveClass = (index: number) => {
    if (index === activeIndex) return 'current active';
    if (index >= activeIndex && index < nextTwo) return 'active';
    return '';
  };

  return (
    <div className="roller">
      <ul>
        {songs.map((item, index) => (
          <li key={item.key} className={getActiveClass(index)}>
            <img src={item.image} alt={item.title} />
            <div className="content">
              <p>{item.title}</p>
              <p className="album">{item.album}</p>
            </div>
          </li>
        ))}
      </ul>
    </div>
  );
}

// src/components/Roller.vue
<template>
    <div class="roller">
        <ul>
            <li v-for="item in songs" :key="item.key" :class="getActive(item.key)">
                <img :src="item.image" alt="">
                <div class="content">
                    <p>{{ item.title }}</p>
                    <p class="album">{{ item.album }}</p>
                </div>
            </li>
        </ul>
    </div>
</template>
<script>
import eventBus from '../eventBus';

export default {
    name: 'Roller',
    props: ['songs'],
    data() {
        return {
            active: 0,
            nextTwo: 3
        }
    },
    mounted() {
        eventBus.$on('currentIndex', (i) => {
            this.active = i;
            this.nextTwo = i + 3;
        });
    },
    methods: {
        getActive(item) {
            let classType = '';
            if (item == this.active) {
                classType = 'current active';
            } else if (item >= this.active && item < this.nextTwo) {
                classType = 'active';
            }
            return classType;
        }
    }
}

</script>
