// app/songs/page.tsx
"use client";

import { useState, useEffect, useMemo } from 'react';
import axios from 'axios';
import Player from '@/components/Player';
import Roller from '@/components/Roller';

interface Song {
  title: string;
  source: string;
  image: string;
  album: string;
  key: number;
}

export default function SongsPage() {
  const [songs, setSongs] = useState<any[]>([]);
  const [playlist, setPlaylist] = useState<any>(null);
  const [currentIndex, setCurrentIndex] = useState(0);

  const getPlaylist = async () => {
    try {
      const randomNumber = Math.floor(Math.random() * 9);
      const url = 'https://cors-anywhere.herokuapp.com/https://api.deezer.com/chart';
      const res = await axios.get(url);
      const selectedPlaylist = res.data.playlists.data[randomNumber];
      setPlaylist(selectedPlaylist);
      getSongs(selectedPlaylist.id);
    } catch (error) {
      console.error('Error fetching playlist:', error);
    }
  };

  const getSongs = async (playlistId: number) => {
    try {
      const url = `https://cors-anywhere.herokuapp.com/https://api.deezer.com/playlist/${playlistId}`;
      const res = await axios.get(url);
      setSongs(res.data.tracks.data);
    } catch (error) {
      console.error('Error fetching songs:', error);
    }
  };

  useEffect(() => {
    getPlaylist();
  }, []);

  const formattedSongs = useMemo(() => {
    return songs
      .filter(song => song.title !== '' && song.album.cover_big !== '' && song.preview !== '' && song.album.title !== '')
      .map((song, index) => ({
        title: song.title,
        source: song.preview,
        image: song.album.cover_big,
        album: song.album.title,
        key: index
      }));
  }, [songs]);

  return (
    <section>
      <article className="grid">
        <div className="card">
          {formattedSongs.length > 0 ? (
            <Player 
              songs={formattedSongs} 
              currentIndex={currentIndex} 
              onNext={() => setCurrentIndex(prev => prev + 1)} 
            />
          ) : (
            <div className="spinner"></div>
          )}
        </div>
        <Roller songs={formattedSongs} activeIndex={currentIndex} />
        {playlist && (
          <aside className="playlist">
            <h2>Playlist</h2>
            <img src={playlist.picture_xl} alt={playlist.title} className="playlist-image" />
            <h3>{playlist.title}</h3>
          </aside>
        )}
      </article>
    </section>
  );
}

// src/components/Songs.vue
<template>
    <section>
        <article class="grid">
            <div class="card" v-if="formatedSongs">
                <div>
                    <player :songs="formatedSongs"></player>
                </div>
            </div>
            <aside class="playlist">
                <h2>Playlist</h2>
                <img :src="playlist.picture_xl" :alt="playlist.title" class="playlist-image">
                <h3>{{ playlist.title }}</h3>
            </aside>
        </article>
    </section>
</template>

<script>
import axios from 'axios';
import Player from './Player.vue';

export default {
    name: 'songs',
    components: {
        Player
    },
    data() {
        return {
            songs: [],
            playlist: ""
        }
    },
    created() {
        this.getPlaylist();
    },
    methods: {
        getPlaylist() {

            let randomNumber = Math.floor((Math.random() * 9) + 0);
            let url = 'https://cors-anywhere.herokuapp.com/https://api.deezer.com/chart';
            
            axios.get(url)
                .then(res => {
                    this.playlist = res.data.playlists.data[randomNumber];
                    this.getSongs();
                }).catch(error => {
                    console.log('erro', error);
                })

        },
        getSongs() {

            let playlistId = this.playlist.id;
            let url = `https://cors-anywhere.herokuapp.com/https://api.deezer.com/playlist/${playlistId}`;

            axios.get(url)
                .then((res) => {
                    this.songs = res.data.tracks.data;
                })
                .catch((error) => console.log(error));
        }
    },

    computed: {
        formatedSongs() {
            let formatedSongs = [];
            let i = 0;
            for (var index in this.songs) {
                if (this.songs[index].title !== '' && this.songs[index].album.cover_big !== '' && this.songs[index].preview !== '') {
                    formatedSongs[i] = {
                        title: this.songs[index].title,
                        source: this.songs[index].preview,
                        image: this.songs[index].album.cover_big
                    }
                    i++;
                }
            }

            return formatedSongs;
        }
    }
}
</script>
